//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models.myDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydatabaseEntities : DbContext
    {
        public mydatabaseEntities()
            : base("name=mydatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_basket> tb_basket { get; set; }
        public virtual DbSet<tb_basket_item> tb_basket_item { get; set; }
        public virtual DbSet<tb_category> tb_category { get; set; }
        public virtual DbSet<tb_category_ml> tb_category_ml { get; set; }
        public virtual DbSet<tb_department> tb_department { get; set; }
        public virtual DbSet<tb_department_ml> tb_department_ml { get; set; }
        public virtual DbSet<tb_dept_cat_images> tb_dept_cat_images { get; set; }
        public virtual DbSet<tb_history_item> tb_history_item { get; set; }
        public virtual DbSet<tb_product> tb_product { get; set; }
        public virtual DbSet<tb_product_images> tb_product_images { get; set; }
        public virtual DbSet<tb_product_sale> tb_product_sale { get; set; }
        public virtual DbSet<tb_rating> tb_rating { get; set; }
        public virtual DbSet<tb_users> tb_users { get; set; }
    }
}
