//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models.myDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_basket_item
    {
        public int basket_item_pk { get; set; }
        public int basket_item_basket_fk { get; set; }
        public int basket_item_product_fk { get; set; }
        public string basket_item_product_name { get; set; }
        public int basket_item_product_price { get; set; }
        public int basket_item_count { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public System.DateTime createdondate { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> lastupdateddate { get; set; }
        public string lastupdatedby { get; set; }
    
        public virtual tb_basket tb_basket { get; set; }
        public virtual tb_product tb_product { get; set; }
    }
}
