//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models.myDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_basket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_basket()
        {
            this.tb_basket_item = new HashSet<tb_basket_item>();
        }
    
        public int basket_pk { get; set; }
        public int basket_user_fk { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public System.DateTime createdondate { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> lastupdateddate { get; set; }
        public string lastupdatedby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_basket_item> tb_basket_item { get; set; }
    }
}
