//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models.myDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_category()
        {
            this.tb_category_ml = new HashSet<tb_category_ml>();
            this.tb_dept_cat_images = new HashSet<tb_dept_cat_images>();
        }
    
        public int category_pk { get; set; }
        public string category_name { get; set; }
        public int category_department_fk { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public System.DateTime createdondate { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> lastupdateddate { get; set; }
        public string lastupdatedby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_category_ml> tb_category_ml { get; set; }
        public virtual tb_department tb_department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_dept_cat_images> tb_dept_cat_images { get; set; }
    }
}
