//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models.myDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_category_ml
    {
        public int category_ml_pk { get; set; }
        public int category_ml_category_fk { get; set; }
        public int category_ml_user_fk { get; set; }
        public float category_ml_count { get; set; }
    
        public virtual tb_category tb_category { get; set; }
        public virtual tb_users tb_users { get; set; }
    }
}
