//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models.myDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_images
    {
        public int prod_image_pk { get; set; }
        public int prod_id { get; set; }
        public byte[] prod_image_data { get; set; }
        public bool prod_main_photo { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public System.DateTime createdondate { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> lastupdateddate { get; set; }
        public string lastupdatedby { get; set; }
    
        public virtual tb_product tb_product { get; set; }
    }
}
