//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models.myDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_rating
    {
        public int rating_pk { get; set; }
        public int rating_product_fk { get; set; }
        public int rating_user_fk { get; set; }
        public float rating_item { get; set; }
    
        public virtual tb_product tb_product { get; set; }
        public virtual tb_users tb_users { get; set; }
    }
}
